// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Adjusts the workout plan weekly based on the user's progress and feedback.
 *
 * - adaptWorkoutPlan - A function that handles the workout plan adjustment process.
 * - AdaptWorkoutPlanInput - The input type for the adaptWorkoutPlan function.
 * - AdaptWorkoutPlanOutput - The return type for the adaptWorkoutPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AdaptWorkoutPlanInputSchema = z.object({
  userId: z.string().describe('The ID of the user.'),
  currentWorkoutPlan: z.string().describe('The current workout plan of the user.'),
  weeklyProgress: z.string().describe('The user weekly progress and feedback on current workout plan.'),
  fitnessGoals: z.string().describe('The fitness goals of the user.'),
  availableEquipment: z.string().describe('The equipment the user has access to.'),
});
export type AdaptWorkoutPlanInput = z.infer<typeof AdaptWorkoutPlanInputSchema>;

const AdaptWorkoutPlanOutputSchema = z.object({
  adjustedWorkoutPlan: z.string().describe('The adjusted workout plan based on user progress and feedback.'),
});
export type AdaptWorkoutPlanOutput = z.infer<typeof AdaptWorkoutPlanOutputSchema>;

export async function adaptWorkoutPlan(input: AdaptWorkoutPlanInput): Promise<AdaptWorkoutPlanOutput> {
  return adaptWorkoutPlanFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adaptWorkoutPlanPrompt',
  input: {schema: AdaptWorkoutPlanInputSchema},
  output: {schema: AdaptWorkoutPlanOutputSchema},
  prompt: `You are a personal trainer that adapts workout plans.

  Based on the user's current workout plan, weekly progress, fitness goals and available equipment, you will adjust the workout plan to optimize results.

  User ID: {{{userId}}}
  Current Workout Plan: {{{currentWorkoutPlan}}}
  Weekly Progress: {{{weeklyProgress}}}
  Fitness Goals: {{{fitnessGoals}}}
  Available Equipment: {{{availableEquipment}}}

  Adjusted Workout Plan:`, // The adjusted workout plan will be returned here
});

const adaptWorkoutPlanFlow = ai.defineFlow(
  {
    name: 'adaptWorkoutPlanFlow',
    inputSchema: AdaptWorkoutPlanInputSchema,
    outputSchema: AdaptWorkoutPlanOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {adjustedWorkoutPlan: output!.adjustedWorkoutPlan!};
  }
);
