[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[build.environment]
  NODE_VERSION = "22"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
